image: ghcr.io/cirruslabs/flutter:3.24.1

pipelines:
  branches:
    'development':
      - step:
          name: APK Assembling
          size: 2x
          deployment: Dev
          caches:
            - gradle
          script:
            - sed -i "s#BASE_URL=#BASE_URL=$BASE_URL#g" .env
            - sed -i "s#BASE_URL_WALLET=#BASE_URL_WALLET=$BASE_URL_WALLET#g" .env
            - flutter pub get
            - flutter gen-l10n
            - flutter packages pub run build_runner build --delete-conflicting-outputs
            - flutter analyze --no-fatal-infos --no-fatal-warnings
            - echo "Building APK"
            - flutter build apk --debug
            - pipe: atlassian/bitbucket-upload-file:0.1.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "build/app/outputs/flutter-apk/app-debug.apk"
          artifacts:
            - build/app/outputs/apk/**
