import 'package:flutter/material.dart';

abstract class AppCustomColors {
  Color get primary;
  Color get secondary;
  Color get terciary;
  Color get accent;
  Color get scaffoldColor;
  Color get cardColor;
  Color get inputColor;
  Color get primaryText;
  Color get secondaryText;
  Color get tertiaryText;
  Color get accentText;
  Color get lightText;
  Color get darkText;
  Color get errorText;
  Color get successText;
  Color get buttonColor;
  Color get buttonTextColor;
  Color get disabledButtonColor;
  Color get disabledButtonTextColor;
  Color get primaryIcon;
  Color get secondaryIcon;
  Color get shadowCardColor;
  Color get headerBackgroundColor;
  Color get headerActionsBackgroundColor;
  Color get alertLink;
  Color get alertBorder;
  Color get clearButtonColor;
  Color get modalBarrierColor;
  Color get circleIconColor;
  Color get cardBackgroundColor;
  Color get avatarBorder;
  LinearGradient get backgroundGradient;
  Color get errorColor;
  Color get lineColor;
  Color get buttonBorderColor;
  Color get secondaryButtonBorderColor;
  Color get modalPrincipalColor;
  Color get buttonTertiaryColor;
  LinearGradient get buttonGradientColor;
}
